server:
  port: 8080

jwt:
  secret: mySecretKey
  expiration: 86400 # ???

spring:
  application:
    name: lab-manage-system
  datasource:
    url: jdbc:mysql://localhost:3306/lab_manage_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.ck.labmanagesystem.entity
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.ck.labmanagesystem: debug